//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDataAnalyzer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMARTPayEntities : DbContext
    {
        public SMARTPayEntities()
            : base("name=SMARTPayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<XRM1CurrentTransactions> XRM1CurrentTransactions { get; set; }
        public virtual DbSet<SysUser> SysUsers { get; set; }
        public virtual DbSet<XRM1ActivePayrollDays> XRM1ActivePayrollDays { get; set; }
    }
}
