//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDataAnalyzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Active { get; set; }
        public bool SysAdmin { get; set; }
        public bool PrivateToCompany { get; set; }
        public short SysSecurityRoleId { get; set; }
        public short UserLevel { get; set; }
        public short SysUserGroupId { get; set; }
        public string Email { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime LastModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> LastPasswordChange { get; set; }
        public bool Locked { get; set; }
        public bool LoggedIn { get; set; }
        public byte LoginAttempts { get; set; }
        public Nullable<System.DateTime> LastReactivated { get; set; }
        public bool RestrictOrganizationalAccess { get; set; }
        public bool RestrictBranchAccess { get; set; }
        public bool RestrictDeptAccess { get; set; }
        public bool RestrictLocationAccess { get; set; }
    }
}
